// Code generated by MockGen. DO NOT EDIT.
// Source: payment_repository.go
//
// Generated by this command:
//
//	mockgen -source=payment_repository.go -destination=../mocks/mock_payment_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/shakilaaulia/Dealan/payment-service/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentRepository is a mock of PaymentRepository interface.
type MockPaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentRepositoryMockRecorder is the mock recorder for MockPaymentRepository.
type MockPaymentRepositoryMockRecorder struct {
	mock *MockPaymentRepository
}

// NewMockPaymentRepository creates a new mock instance.
func NewMockPaymentRepository(ctrl *gomock.Controller) *MockPaymentRepository {
	mock := &MockPaymentRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRepository) EXPECT() *MockPaymentRepositoryMockRecorder {
	return m.recorder
}

// GetTransactionStatus mocks base method.
func (m *MockPaymentRepository) GetTransactionStatus(ctx context.Context, transactionID string) (domain.PaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionStatus", ctx, transactionID)
	ret0, _ := ret[0].(domain.PaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionStatus indicates an expected call of GetTransactionStatus.
func (mr *MockPaymentRepositoryMockRecorder) GetTransactionStatus(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionStatus", reflect.TypeOf((*MockPaymentRepository)(nil).GetTransactionStatus), ctx, transactionID)
}

// ProcessGateway mocks base method.
func (m *MockPaymentRepository) ProcessGateway(ctx context.Context, transactionID string, nominal float64, metode string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessGateway", ctx, transactionID, nominal, metode)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessGateway indicates an expected call of ProcessGateway.
func (mr *MockPaymentRepositoryMockRecorder) ProcessGateway(ctx, transactionID, nominal, metode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessGateway", reflect.TypeOf((*MockPaymentRepository)(nil).ProcessGateway), ctx, transactionID, nominal, metode)
}

// SaveTransaction mocks base method.
func (m *MockPaymentRepository) SaveTransaction(ctx context.Context, req domain.PaymentRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTransaction", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveTransaction indicates an expected call of SaveTransaction.
func (mr *MockPaymentRepositoryMockRecorder) SaveTransaction(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTransaction", reflect.TypeOf((*MockPaymentRepository)(nil).SaveTransaction), ctx, req)
}
