// Code generated by MockGen. DO NOT EDIT.
// Source: repository/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=repository/interfaces.go -destination=mocks/mock_rating_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/shakilaaulia/Dealan/rating-review-service/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRatingRepository is a mock of RatingRepository interface.
type MockRatingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRatingRepositoryMockRecorder
	isgomock struct{}
}

// MockRatingRepositoryMockRecorder is the mock recorder for MockRatingRepository.
type MockRatingRepositoryMockRecorder struct {
	mock *MockRatingRepository
}

// NewMockRatingRepository creates a new mock instance.
func NewMockRatingRepository(ctrl *gomock.Controller) *MockRatingRepository {
	mock := &MockRatingRepository{ctrl: ctrl}
	mock.recorder = &MockRatingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRatingRepository) EXPECT() *MockRatingRepositoryMockRecorder {
	return m.recorder
}

// GetAverageRating mocks base method.
func (m *MockRatingRepository) GetAverageRating(ctx context.Context, targetID string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAverageRating", ctx, targetID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAverageRating indicates an expected call of GetAverageRating.
func (mr *MockRatingRepositoryMockRecorder) GetAverageRating(ctx, targetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAverageRating", reflect.TypeOf((*MockRatingRepository)(nil).GetAverageRating), ctx, targetID)
}

// SaveReview mocks base method.
func (m *MockRatingRepository) SaveReview(ctx context.Context, req domain.RatingRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveReview", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveReview indicates an expected call of SaveReview.
func (mr *MockRatingRepositoryMockRecorder) SaveReview(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveReview", reflect.TypeOf((*MockRatingRepository)(nil).SaveReview), ctx, req)
}
