// Code generated by MockGen. DO NOT EDIT.
// Source: repository/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=repository/interfaces.go -destination=mocks/mock_punishment_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/shakilaaulia/Dealan/punishment-service/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPunishmentRepository is a mock of PunishmentRepository interface.
type MockPunishmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPunishmentRepositoryMockRecorder
	isgomock struct{}
}

// MockPunishmentRepositoryMockRecorder is the mock recorder for MockPunishmentRepository.
type MockPunishmentRepositoryMockRecorder struct {
	mock *MockPunishmentRepository
}

// NewMockPunishmentRepository creates a new mock instance.
func NewMockPunishmentRepository(ctrl *gomock.Controller) *MockPunishmentRepository {
	mock := &MockPunishmentRepository{ctrl: ctrl}
	mock.recorder = &MockPunishmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPunishmentRepository) EXPECT() *MockPunishmentRepositoryMockRecorder {
	return m.recorder
}

// StoreViolation mocks base method.
func (m *MockPunishmentRepository) StoreViolation(ctx context.Context, req domain.PunishmentRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreViolation", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreViolation indicates an expected call of StoreViolation.
func (mr *MockPunishmentRepositoryMockRecorder) StoreViolation(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreViolation", reflect.TypeOf((*MockPunishmentRepository)(nil).StoreViolation), ctx, req)
}

// UpdateAccountStatus mocks base method.
func (m *MockPunishmentRepository) UpdateAccountStatus(ctx context.Context, id, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccountStatus indicates an expected call of UpdateAccountStatus.
func (mr *MockPunishmentRepositoryMockRecorder) UpdateAccountStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountStatus", reflect.TypeOf((*MockPunishmentRepository)(nil).UpdateAccountStatus), ctx, id, status)
}
