// Code generated by MockGen. DO NOT EDIT.
// Source: domain/location.go
//
// Generated by this command:
//
//	mockgen -source=domain/location.go -destination=mocks/mock_location.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "location-service/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLocationRepository is a mock of LocationRepository interface.
type MockLocationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLocationRepositoryMockRecorder
	isgomock struct{}
}

// MockLocationRepositoryMockRecorder is the mock recorder for MockLocationRepository.
type MockLocationRepositoryMockRecorder struct {
	mock *MockLocationRepository
}

// NewMockLocationRepository creates a new mock instance.
func NewMockLocationRepository(ctrl *gomock.Controller) *MockLocationRepository {
	mock := &MockLocationRepository{ctrl: ctrl}
	mock.recorder = &MockLocationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocationRepository) EXPECT() *MockLocationRepositoryMockRecorder {
	return m.recorder
}

// SaveLocation mocks base method.
func (m *MockLocationRepository) SaveLocation(loc *domain.LocationUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLocation", loc)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveLocation indicates an expected call of SaveLocation.
func (mr *MockLocationRepositoryMockRecorder) SaveLocation(loc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLocation", reflect.TypeOf((*MockLocationRepository)(nil).SaveLocation), loc)
}
