// Code generated by MockGen. DO NOT EDIT.
// Source: shipment_repository.go
//
// Generated by this command:
//
//	mockgen -source=shipment_repository.go -destination=../mocks/mock_shipment_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/shakilaaulia/Dealan/shipment-service/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockShipmentRepository is a mock of ShipmentRepository interface.
type MockShipmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShipmentRepositoryMockRecorder
	isgomock struct{}
}

// MockShipmentRepositoryMockRecorder is the mock recorder for MockShipmentRepository.
type MockShipmentRepositoryMockRecorder struct {
	mock *MockShipmentRepository
}

// NewMockShipmentRepository creates a new mock instance.
func NewMockShipmentRepository(ctrl *gomock.Controller) *MockShipmentRepository {
	mock := &MockShipmentRepository{ctrl: ctrl}
	mock.recorder = &MockShipmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShipmentRepository) EXPECT() *MockShipmentRepositoryMockRecorder {
	return m.recorder
}

// CreateShipment mocks base method.
func (m *MockShipmentRepository) CreateShipment(ctx context.Context, req domain.ShipmentRequest) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShipment", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateShipment indicates an expected call of CreateShipment.
func (mr *MockShipmentRepositoryMockRecorder) CreateShipment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShipment", reflect.TypeOf((*MockShipmentRepository)(nil).CreateShipment), ctx, req)
}

// GenerateLabel mocks base method.
func (m *MockShipmentRepository) GenerateLabel(ctx context.Context, shipmentID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateLabel", ctx, shipmentID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateLabel indicates an expected call of GenerateLabel.
func (mr *MockShipmentRepositoryMockRecorder) GenerateLabel(ctx, shipmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateLabel", reflect.TypeOf((*MockShipmentRepository)(nil).GenerateLabel), ctx, shipmentID)
}

// SaveProof mocks base method.
func (m *MockShipmentRepository) SaveProof(ctx context.Context, shipmentID string, proof domain.ProofData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveProof", ctx, shipmentID, proof)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveProof indicates an expected call of SaveProof.
func (mr *MockShipmentRepositoryMockRecorder) SaveProof(ctx, shipmentID, proof any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveProof", reflect.TypeOf((*MockShipmentRepository)(nil).SaveProof), ctx, shipmentID, proof)
}
