// Code generated by MockGen. DO NOT EDIT.
// Source: map-route-service/repository (interfaces: MapRepository)
//
// Generated by this command:
//
//	mockgen map-route-service/repository MapRepository
//

// Package mock_repository is a generated GoMock package.
package mocks

import (
	context "context"
	domain "map-route-service/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMapRepository is a mock of MapRepository interface.
type MockMapRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMapRepositoryMockRecorder
	isgomock struct{}
}

// MockMapRepositoryMockRecorder is the mock recorder for MockMapRepository.
type MockMapRepositoryMockRecorder struct {
	mock *MockMapRepository
}

// NewMockMapRepository creates a new mock instance.
func NewMockMapRepository(ctrl *gomock.Controller) *MockMapRepository {
	mock := &MockMapRepository{ctrl: ctrl}
	mock.recorder = &MockMapRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapRepository) EXPECT() *MockMapRepositoryMockRecorder {
	return m.recorder
}

// GetRoute mocks base method.
func (m *MockMapRepository) GetRoute(ctx context.Context, origin, destination string) (*domain.RouteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoute", ctx, origin, destination)
	ret0, _ := ret[0].(*domain.RouteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoute indicates an expected call of GetRoute.
func (mr *MockMapRepositoryMockRecorder) GetRoute(ctx, origin, destination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoute", reflect.TypeOf((*MockMapRepository)(nil).GetRoute), ctx, origin, destination)
}
