// Code generated by MockGen. DO NOT EDIT.
// Source: domain/matching.go
//
// Generated by this command:
//
//	mockgen -source=domain/matching.go -destination=mocks/mock_matching.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "matching-service/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMatchingRepository is a mock of MatchingRepository interface.
type MockMatchingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMatchingRepositoryMockRecorder
	isgomock struct{}
}

// MockMatchingRepositoryMockRecorder is the mock recorder for MockMatchingRepository.
type MockMatchingRepositoryMockRecorder struct {
	mock *MockMatchingRepository
}

// NewMockMatchingRepository creates a new mock instance.
func NewMockMatchingRepository(ctrl *gomock.Controller) *MockMatchingRepository {
	mock := &MockMatchingRepository{ctrl: ctrl}
	mock.recorder = &MockMatchingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchingRepository) EXPECT() *MockMatchingRepositoryMockRecorder {
	return m.recorder
}

// FindNearestDriver mocks base method.
func (m *MockMatchingRepository) FindNearestDriver(req *domain.MatchingRequest) (*domain.MatchingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNearestDriver", req)
	ret0, _ := ret[0].(*domain.MatchingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNearestDriver indicates an expected call of FindNearestDriver.
func (mr *MockMatchingRepositoryMockRecorder) FindNearestDriver(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNearestDriver", reflect.TypeOf((*MockMatchingRepository)(nil).FindNearestDriver), req)
}
