// Code generated by MockGen. DO NOT EDIT.
// Source: pricing_repository.go
//
// Generated by this command:
//
//	mockgen -source=pricing_repository.go -destination=../mocks/mock_pricing_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/shakilaaulia/Dealan/pricing-service/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPricingRepository is a mock of PricingRepository interface.
type MockPricingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPricingRepositoryMockRecorder
	isgomock struct{}
}

// MockPricingRepositoryMockRecorder is the mock recorder for MockPricingRepository.
type MockPricingRepositoryMockRecorder struct {
	mock *MockPricingRepository
}

// NewMockPricingRepository creates a new mock instance.
func NewMockPricingRepository(ctrl *gomock.Controller) *MockPricingRepository {
	mock := &MockPricingRepository{ctrl: ctrl}
	mock.recorder = &MockPricingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPricingRepository) EXPECT() *MockPricingRepositoryMockRecorder {
	return m.recorder
}

// GetBasePrice mocks base method.
func (m *MockPricingRepository) GetBasePrice(ctx context.Context, serviceType string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBasePrice", ctx, serviceType)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBasePrice indicates an expected call of GetBasePrice.
func (mr *MockPricingRepositoryMockRecorder) GetBasePrice(ctx, serviceType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBasePrice", reflect.TypeOf((*MockPricingRepository)(nil).GetBasePrice), ctx, serviceType)
}

// SaveNegotiation mocks base method.
func (m *MockPricingRepository) SaveNegotiation(ctx context.Context, data domain.NegotiationData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveNegotiation", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveNegotiation indicates an expected call of SaveNegotiation.
func (mr *MockPricingRepositoryMockRecorder) SaveNegotiation(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveNegotiation", reflect.TypeOf((*MockPricingRepository)(nil).SaveNegotiation), ctx, data)
}
