// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository (interfaces: PromoRepository)
//
// Generated by this command:
//
//	mockgen ./repository PromoRepository
//

// Package mock_repository is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPromoRepository is a mock of PromoRepository interface.
type MockPromoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPromoRepositoryMockRecorder
	isgomock struct{}
}

// MockPromoRepositoryMockRecorder is the mock recorder for MockPromoRepository.
type MockPromoRepositoryMockRecorder struct {
	mock *MockPromoRepository
}

// NewMockPromoRepository creates a new mock instance.
func NewMockPromoRepository(ctrl *gomock.Controller) *MockPromoRepository {
	mock := &MockPromoRepository{ctrl: ctrl}
	mock.recorder = &MockPromoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromoRepository) EXPECT() *MockPromoRepositoryMockRecorder {
	return m.recorder
}

// CheckPromo mocks base method.
func (m *MockPromoRepository) CheckPromo(ctx context.Context, code string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPromo", ctx, code)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPromo indicates an expected call of CheckPromo.
func (mr *MockPromoRepositoryMockRecorder) CheckPromo(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPromo", reflect.TypeOf((*MockPromoRepository)(nil).CheckPromo), ctx, code)
}
